apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml

replicas:
  - name: vote
    count: 7

images:
  - name: schoolofdevops/vote
    newTag: v4

namespace: instavote

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported-by: "dandy@sre.com"


#configMapGenerator:
#  - name: vote
#    literals:
#      - OPTION_A=FluxCD
#      - OPTION_B=ArgoCD

configMapGenerator:
  - name: vote
    envs:
      - options.env
