kind: Deployment
metadata:
  labels:
    app: worker
    tier: back
  name: worker
spec:
  replicas: 7
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        tier: back
    spec:
      containers:
      - image: schoolofdevops/worker:latest
        name: worker
