apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker
    tier: front
  name: worker
spec:
  replicas: 5
  template:
    spec:
      containers:
      - image: schoolofdevops/worker:latest
        name: worker
