apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml

replicas:
  - name: worker
    count: 1


namespace: instavote

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported-by: "dandy@sre.com"

