apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker
    tier: front
  name: worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: worker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker
        tier: front
    spec:
      containers:
      - image: nhiuana/worker:master
        name: worker
        resources: {}
